#! /bin/sh
# send_host_check v0.0
# uses nsca to send encrypted passive host check result to monitoring host

MON_HOST="your.monitoringhost.com"

# run some command here to check host health; note the first command below
# does not return 0 when status is started
#run_init rc-service foo-service status > /dev/null 2>&1

LOAD=$(cat /proc/loadavg | cut -c1)

EL=$?

if [ $EL -ne 0 ] || [ $LOAD -gt 2 ]; then
  MESSAGE="WARNING: Load is > 2"
  STATE=1
else
  MESSAGE="HOST OK: Health is good"
  STATE=0
fi

echo "${HOSTNAME}.yourdomain.com;$STATE;$MESSAGE" | /usr/bin/send_nsca \
    -H "${MON_HOST}" -d ";" -c /etc/nagios/send_nsca.cfg
